version: '3.8'
services:
  jenkins:
    image: danieldev128/my-jenkis-repo:latest  # Usa la imagen descargada
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
    driver: local